# -*- coding: utf-8 -*-
# @Time : 2020/7/31 2:56 下午
# @Author : SongWeinan
# @Software: PyCharm
# 欲买桂花同载酒，终不似、少年游。
# ======================================================================================================================
from yacs.config import CfgNode as CN

_C = CN()

_C.DATA = CN()
# 数据集名字
_C.DATA.NAMES = []
# 数据集文件夹
_C.DATA.DIRS = []

_C.AUGMENT = CN()
# 模型输入图片大小
_C.AUGMENT.INPUT_SHAPE = (512, 512)
# 裁剪最大尝试次数
_C.AUGMENT.MAX_TRY_TIMES = 30
# 翻转比例
_C.AUGMENT.FLIP = 0.
# zoom in样本占比
_C.AUGMENT.ZOOM_IN = 0.5
# crop比例
_C.AUGMENT.MIN_SCALE = 0.5
# pad比例
_C.AUGMENT.MAX_SCALE = 4.
# resize范围
_C.AUGMENT.ASPECT_RATIO = (1., 1.)
# 平移范围
_C.AUGMENT.TRANSLATE_PRESENT = (-0.1, 0.1)
# 旋转范围
_C.AUGMENT.ROTATE = (-5, 5)
# 仿射变换范围
_C.AUGMENT.SHEAR = (-5, 5)
# 透视变换范围
_C.AUGMENT.PERSPECTIVE_TRANSFORM = (0.0, 0.1)
# 明暗变化范围
_C.AUGMENT.BRIGHTNESS = (0.5, 1.5)
# 色相变化范围
_C.AUGMENT.HUE = (0.5, 1.5)
# 饱和度变化范围
_C.AUGMENT.SATURATION = (0.5, 1.5)
# 增强背景
_C.AUGMENT.BACKGROUND = True

_C.MODEL = CN()
_C.MODEL.CODERS = ['']

_C.MODEL.EAST = CN()
_C.MODEL.EAST.INPUT_LAYER = 'fuse'
_C.MODEL.EAST.STRIDE = 4
_C.MODEL.EAST.TEXT_SCALE = 512
_C.MODEL.EAST.SCORE_WEIGHT = 1.
_C.MODEL.EAST.DISTANCE_WEIGHT = 1.
_C.MODEL.EAST.ROTATION_WEIGHT = 10.
_C.MODEL.EAST.SCORES_THRESH = 0.8

_C.MODEL.DB = CN()
_C.MODEL.DB.RATE = 0.4
_C.MODEL.DB.INPUT_LAYER = 'fuse'
_C.MODEL.DB.STRIDE = 4
_C.MODEL.DB.BINARY_WEIGHT = 1.
_C.MODEL.DB.PROBABILITY_WEIGHT = 1.
_C.MODEL.DB.SHRESHOLD_WEIGHT = 10.
_C.MODEL.DB.SCORES_THRESH = 0.8

_C.MODEL.PSE = CN()
_C.MODEL.PSE.INPUT_LAYER = 'fuse'
_C.MODEL.PSE.STRIDE = 4
_C.MODEL.PSE.M = 0.5
_C.MODEL.PSE.N = 6
_C.MODEL.PSE.COMPLETE_WEIGHT = 0.7
_C.MODEL.PSE.SHRUNK_WEIGHT = 0.3
_C.MODEL.PSE.SCORES_THRESH = 0.8

_C.MODEL.SEMANTIC = CN()
_C.MODEL.SEMANTIC.INPUT_LAYER = 'fuse'
_C.MODEL.SEMANTIC.STRIDE = 4
_C.MODEL.SEMANTIC.SEMANTIC_WEIGHT = 1.
_C.MODEL.SEMANTIC.SCORES_THRESH = 0.8

_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.NAME = ''
_C.MODEL.BACKBONE.NORM = 'FrozenBN'
_C.MODEL.BACKBONE.PRETRAINED = False
_C.MODEL.BACKBONE.PRETRAINED_DIR = ''
_C.MODEL.BACKBONE.FREEZE_AT = 0

_C.MODEL.META_ARCH = CN()
_C.MODEL.META_ARCH.NAME = ''
_C.MODEL.META_ARCH.NORM = ''
_C.MODEL.META_ARCH.USE_FUSE = False
_C.MODEL.META_ARCH.USE_P6P7 = False
_C.MODEL.META_ARCH.INTER_PLANES = 256
_C.MODEL.META_ARCH.OUT_PLANES = 256

_C.MODEL.HEAD = CN()
_C.MODEL.HEAD.NORM = 'GN'

_C.SOLVER = CN()
_C.SOLVER.DEVICE = 'cpu'
_C.SOLVER.WEIGHTS = ''
_C.SOLVER.SAVE_DIR = 'checkpoints'
_C.SOLVER.CHECKPOINT_NAME = 'model'
_C.SOLVER.CHECKPOINT_PERIOD = 500
_C.SOLVER.BATCH_SIZE = 1
_C.SOLVER.NUM_WORKS = 0
_C.SOLVER.PIN_MEMORY = False
_C.SOLVER.OPTIMIZER = 'Adam'
# 最大迭代次数
_C.SOLVER.MAX_ITERS = 10000
_C.SOLVER.WEIGHT_DECAY = 0.00001
_C.SOLVER.LR = CN()
_C.SOLVER.LR.NAME = 'WarmupCosineLR'
# 基础学习率
_C.SOLVER.LR.BASE_LR = 0.001
# warm step
_C.SOLVER.LR.WARMUP_ITERS = 1000
# warm起始学习率与终止学习率的比
_C.SOLVER.LR.WARMUP_FACTOR = 0.01
# 阶梯下降步数站总步数比
_C.SOLVER.LR.MILESTONES = [0.2, 0.5, 0.8]
# 下降比
_C.SOLVER.LR.GAMMA = 0.1


_C.SOLVER.TENSORBOARD_WRITER = CN()
# tensoboard日志文件夹
_C.SOLVER.TENSORBOARD_WRITER.LOG_DIR = '../logs'
# tensoboard sclalar记录周期
_C.SOLVER.TENSORBOARD_WRITER.SCALAR_PERIOD = 5
# tensorboard image记录周期
_C.SOLVER.TENSORBOARD_WRITER.IMAGE_PERIOD = 10





